import { useState } from 'react';
import { ArrowRight, Bot, Brain, MessageSquare, Settings2 } from 'lucide-react';
import { isTerminal, type Agent, type OfficeSnapshot } from '@super-system/core';
import { errorMessage } from '../api';
import { useWorkspace, type WorkspacePage } from '../context';
import { usePollingResource } from '../management-ui';
import { Badge, Button, EmptyState, ErrorNotice, Loading, PageHeader, SearchField } from '../ui';

export function Agents() {
  const { agent: selected, preferences, setPreferences, setConversationId, navigate } = useWorkspace(); const office = usePollingResource<OfficeSnapshot>('/office'); const [search, setSearch] = useState(''); const [busy, setBusy] = useState<string>(); const [error, setError] = useState<string>();
  const choose = async (agent: Agent, page: WorkspacePage) => { setBusy(agent.id); setError(undefined); try { await setPreferences({ ...preferences, selectedAgentId: agent.id }); setConversationId(undefined); navigate(page); } catch (cause) { setError(errorMessage(cause)); } finally { setBusy(undefined); } };
  const agents = (office.data?.agents || []).filter(agent => `${agent.name} ${agent.id} ${agent.model || ''}`.toLowerCase().includes(search.toLowerCase()));
  return <div className="page control-page"><PageHeader eyebrow="Agent overview" title="Your team, together." description="Existing agents, their models, and the work observed in this workspace." /><div className="control-toolbar"><SearchField value={search} onChange={setSearch} placeholder="Find an agent…" /><Badge>{office.data?.agents.length || 0} agents</Badge></div>{(error || office.error) && <ErrorNotice message={error || office.error!} retry={office.refresh} />}
    {office.loading && !office.data ? <Loading /> : agents.length ? <div className="control-card-grid">{agents.map(agent => { const runs = office.data!.runs.filter(run => run.agentId === agent.id); const active = runs.find(run => !isTerminal(run.status) && !run.releasedAt); return <article className={`panel control-card agent-card ${agent.id === selected?.id ? 'agent-card-selected' : ''}`} key={agent.id}><div className="control-card-top"><span className="agent-portrait"><Bot size={29} strokeWidth={1.4} /></span><Badge tone={active?.status === 'waiting_for_approval' || active?.status === 'interrupted' ? 'warn' : active ? 'good' : 'neutral'}>{active ? active.status.replaceAll('_', ' ') : 'No active workspace run'}</Badge></div><h2>{agent.name}</h2><span className="mono quiet-label">{agent.id.slice(-8)}{agent.id === selected?.id ? ' · Selected' : ''}</span><p>{agent.description || 'An existing Letta agent.'}</p><dl className="agent-facts"><div><dt>Model</dt><dd className="mono">{agent.model || 'Not reported'}</dd></div><div><dt>Recent workspace runs</dt><dd>{runs.length}</dd></div><div><dt>Open planning tasks</dt><dd>{office.data!.tasks.filter(task => task.agentId === agent.id && task.status !== 'done').length}</dd></div></dl><footer><Button variant="primary" busy={busy === agent.id} disabled={Boolean(busy)} onClick={() => { void choose(agent, 'chat'); }}><MessageSquare size={14} />Chat<ArrowRight size={13} /></Button><div><Button variant="ghost" disabled={Boolean(busy)} onClick={() => { void choose(agent, 'config'); }} aria-label={`Configure ${agent.name}`}><Settings2 size={15} /></Button><Button variant="ghost" disabled={Boolean(busy)} onClick={() => { void choose(agent, 'memory'); }} aria-label={`Memory for ${agent.name}`}><Brain size={15} /></Button></div></footer></article>; })}</div> : <EmptyState icon={Bot} title={search ? 'No matching agents' : 'Your agents will appear here.'}><p>{search ? 'Search by name, model, or ID.' : 'Connect your existing Letta runtime in System to load its agents.'}</p></EmptyState>}
    <div className="control-note"><Bot size={17} /><p>Activity here covers the latest 200 workspace runs. Agents may also be working through the CLI or other clients; their remote process state is not inferred from this list.</p></div>
  </div>;
}
