import { useEffect, useState, type FormEvent } from 'react';
import { RotateCcw, Save, Settings2, ShieldCheck } from 'lucide-react';
import { agentConfigFields, type AgentConfiguration } from '@super-system/core';
import { api, errorMessage, segment } from '../api';
import { useWorkspace } from '../context';
import { useResource } from '../hooks';
import { Button, CapabilityNotice, ErrorNotice, Field, Loading, PageHeader } from '../ui';

export function Config() {
  const { agent, connection, refreshConnection, notify } = useWorkspace(); const canRead = connection.capabilities.agentConfigRead.state === 'supported';
  const config = useResource<AgentConfiguration>(agent && canRead ? `/agents/${segment(agent.id)}/config` : null);
  const [draft, setDraft] = useState<AgentConfiguration>(); const [busy, setBusy] = useState(false); const [error, setError] = useState<string>();
  useEffect(() => { if (config.data && !draft) setDraft(config.data); }, [config.data, draft]);
  const changes = draft && config.data ? Object.fromEntries(agentConfigFields.filter(key => draft[key] !== config.data![key] && config.data!.editableFields.includes(key)).map(key => [key, draft[key]])) : {};
  const writable = connection.capabilities.agentConfigWrite.state === 'supported';
  const save = async (event: FormEvent) => { event.preventDefault(); if (!agent || !draft) return; setBusy(true); setError(undefined); try { const saved = await api<AgentConfiguration>(`/agents/${segment(agent.id)}/config`, { method: 'PATCH', body: JSON.stringify({ ...changes, expectedVersion: draft.version }) }); setDraft(saved); config.setData(saved); notify('Agent configuration saved.'); await refreshConnection(); } catch (cause) { setError(errorMessage(cause)); } finally { setBusy(false); } };
  return <div className="page control-page"><PageHeader eyebrow="Agent configuration" title="Make the details count." description={agent ? `Settings for ${agent.name}. Changes are saved to your existing Letta agent.` : 'Select an agent to inspect its configuration.'} />
    {!canRead ? <CapabilityNotice icon={Settings2} title="Configuration is unavailable" capability={connection.capabilities.agentConfigRead} /> : <>{config.error && <ErrorNotice message={config.error} retry={config.refresh} />}{!draft ? <Loading label="Reading agent configuration…" /> : <form onSubmit={save} className="panel config-form"><div className="section-heading"><div><h2>{agent?.name}</h2><p className="mono wrap-anywhere">{draft.agentId}</p></div><ShieldCheck size={20} /></div><div className="control-form panel-padding">{error && <ErrorNotice message={error} />}<div className="form-columns"><Field label="Agent name"><input required maxLength={150} value={draft.name} disabled={!writable || !draft.editableFields.includes('name')} onChange={event => setDraft({ ...draft, name: event.target.value })} /></Field><Field label="Model handle" hint="Use a provider/model handle. Existing conversation overrides may keep their model."><input required value={draft.model} disabled={!writable || !draft.editableFields.includes('model')} onChange={event => setDraft({ ...draft, model: event.target.value })} placeholder="provider/model" /></Field></div><Field label="Description"><textarea rows={3} maxLength={2000} value={draft.description} disabled={!writable || !draft.editableFields.includes('description')} onChange={event => setDraft({ ...draft, description: event.target.value })} /></Field><Field label="System instructions" hint="These instructions shape the agent’s behavior. Review the full text before saving."><textarea rows={14} maxLength={100000} className="code-editor" value={draft.system} disabled={!writable || !draft.editableFields.includes('system')} onChange={event => setDraft({ ...draft, system: event.target.value })} /></Field></div><footer className="config-savebar"><span>{Object.keys(changes).length ? `${Object.keys(changes).length} changed fields ready to save` : 'Saved configuration'}</span><div><Button type="button" disabled={busy} onClick={() => { setDraft(undefined); config.setData(undefined); setError(undefined); config.refresh(); }}><RotateCcw size={15} />Reload saved values</Button><Button type="submit" variant="primary" busy={busy} disabled={!writable || !Object.keys(changes).length}><Save size={15} />Save configuration</Button></div></footer></form>}</>}
  </div>;
}
