import { useState } from 'react';
import { ArrowRight, Cable, Check, Monitor, Radio, RefreshCw, Server, ShieldCheck } from 'lucide-react';
import type { GatewayInfo } from '@super-system/core';
import { errorMessage } from '../api';
import { useWorkspace } from '../context';
import { useResource } from '../hooks';
import { Metrics } from '../management-ui';
import { Badge, Button, ErrorNotice, Loading, PageHeader } from '../ui';

export function Gateway() {
  const { refreshConnection } = useWorkspace(); const gateway = useResource<GatewayInfo>('/gateway'); const [busy, setBusy] = useState(false); const [error, setError] = useState<string>(); const data = gateway.data;
  const check = async () => { setBusy(true); setError(undefined); try { await refreshConnection(); gateway.refresh(); } catch (cause) { setError(errorMessage(cause)); } finally { setBusy(false); } };
  return <div className="page control-page"><PageHeader eyebrow="Connection & runtime" title="Every link, in view." description="Follow the path from your workspace to your existing Letta runtime." actions={<Button busy={busy} onClick={check}><RefreshCw size={16} />Check gateway</Button>} />
    {(error || gateway.error) && <ErrorNotice message={error || gateway.error!} retry={gateway.refresh} />}{!data ? <Loading /> : <><section className="panel gateway-path" aria-label="Connection path"><div><span className="control-symbol"><Monitor size={24} /></span><h2>Your workspace</h2><p>Browser or desktop</p><Badge tone="good">Open</Badge></div><ArrowRight className="path-arrow" size={22} /><div><span className="control-symbol"><Cable size={24} /></span><h2>Super System API</h2><p>{Math.floor(data.uptime / 60)} minutes uptime</p><Badge tone="good">Responding</Badge></div><ArrowRight className="path-arrow" size={22} /><div><span className="control-symbol"><Server size={24} /></span><h2>Letta runtime</h2><p>{data.runtime?.backend || data.connection.mode} · {data.runtime?.version || data.connection.version || 'Version unknown'}</p><Badge tone={data.connection.status === 'connected' ? 'good' : 'warn'}>{data.connection.status === 'connected' ? 'Connected' : data.connection.status === 'error' ? 'Connection failed' : 'Not configured'}</Badge></div></section>
    <Metrics values={[{ label: 'Active runs', value: String(data.activeRuns), detail: 'Observed in this workspace' }, { label: 'Awaiting approval', value: String(data.waitingRuns) }, { label: 'Needs review', value: String(data.interruptedRuns) }, { label: 'Enabled MCP servers', value: String(data.mcpEnabled) }]} />
    <div className="control-two-columns"><section className="panel"><div className="section-heading"><div><h2>Transport details</h2><p>The current application connection.</p></div><Radio size={18} /></div><dl className="control-details"><div><dt>Protocol</dt><dd>{data.transport}</dd></div><div><dt>Endpoint</dt><dd className="mono wrap-anywhere">{data.connection.baseUrl || 'Not configured'}</dd></div><div><dt>Latency</dt><dd>{data.connection.latencyMs === undefined ? 'Not measured' : `${data.connection.latencyMs} ms`}</dd></div><div><dt>Last checked</dt><dd>{new Date(data.connection.checkedAt).toLocaleTimeString()}</dd></div></dl>{data.connection.error && <div className="panel-padding"><ErrorNotice message={data.connection.error} /></div>}</section><section className="panel"><div className="section-heading"><div><h2>Runtime capabilities</h2><p>Reported by the connected App Server.</p></div><ShieldCheck size={18} /></div>{data.runtimeError && <div className="panel-padding"><ErrorNotice message={data.runtimeError} /></div>}{data.runtime ? <div className="runtime-flags">{Object.entries(data.runtime.capabilities).map(([key, value]) => <div key={key}><span>{key.replaceAll('_', ' ')}</span><Badge tone={value ? 'good' : 'neutral'}>{value ? <><Check size={11} />Available</> : 'Unavailable'}</Badge></div>)}</div> : <p className="panel-padding muted">This connection does not report App Server diagnostics.</p>}</section></div><div className="control-note"><Radio size={17} /><p>{data.historyCoverage} Keep your SSH connection running when using a forwarded endpoint.</p></div></>}
  </div>;
}
