import { useState, type FormEvent } from 'react';
import { Cable, Pencil, Plus, Server, Trash2, Unplug } from 'lucide-react';
import type { McpInput, McpServer, McpTestResult } from '@super-system/core';
import { api, errorMessage, post, segment } from '../api';
import { useWorkspace } from '../context';
import { useResource } from '../hooks';
import { AgentAssignments, DeleteDialog } from '../management-ui';
import { Badge, Button, EmptyState, ErrorNotice, Field, IconButton, Loading, Modal, PageHeader } from '../ui';

export function Mcp() {
  const { agents, connection, notify } = useWorkspace(); const servers = useResource<McpServer[]>('/mcp');
  const [editing, setEditing] = useState<McpServer | 'new'>(); const [deleting, setDeleting] = useState<McpServer>();
  const [testing, setTesting] = useState<string>(); const [testResults, setTestResults] = useState<Record<string, McpTestResult>>({}); const [testError, setTestError] = useState<string>();
  const test = async (item: McpServer) => { setTesting(item.id); setTestError(undefined); try { const result = await post<McpTestResult>(`/mcp/${segment(item.id)}/test`); setTestResults(previous => ({ ...previous, [item.id]: result })); } catch (cause) { setTestError(`${item.name}: ${errorMessage(cause)}`); } finally { setTesting(undefined); } };
  return <div className="page control-page"><PageHeader eyebrow="Tools & connections" title="A little more capability." description="Connect MCP servers and choose which agents can use their tools." actions={<Button variant="primary" onClick={() => setEditing('new')}><Plus size={16} />Add MCP server</Button>} />
    <div className="control-note"><Cable size={18} /><p>Connections run from the Super System API. Enabled servers supply tools to new workspace runs for assigned agents. Every tool execution asks for your approval. Connection tests discover tools without calling them.</p></div>
    {connection.capabilities.mcp.state !== 'supported' && <div className="control-note"><Unplug size={17} /><p>{connection.capabilities.mcp.reason || 'This provider does not expose session MCP tools. You can prepare and test server configurations here.'}</p></div>}
    {servers.error && <ErrorNotice message={servers.error} retry={servers.refresh} />}{testError && <ErrorNotice message={testError} />}
    {servers.loading && !servers.data ? <Loading /> : servers.data?.length ? <div className="control-card-grid">{servers.data.map(item => <article className="panel control-card" key={item.id}><div className="control-card-top"><span className="control-symbol"><Server size={21} /></span><Badge tone={item.enabled && item.agentIds.length ? 'good' : 'neutral'}>{item.enabled ? item.agentIds.length ? 'Enabled' : 'Unassigned' : 'Disabled'}</Badge></div><h2>{item.name}</h2><span className="quiet-label">{item.transport.toUpperCase()} · {item.hasCredentials ? 'Credentials saved' : 'No saved credentials'}</span><p className="mono wrap-anywhere">{item.transport === 'stdio' ? item.command : item.url}</p><div className="assignment-tags">{item.agentIds.map(id => <span key={id}>{agents.find(agent => agent.id === id)?.name || id.slice(-8)}</span>)}</div>{testResults[item.id] && <details className="mcp-tools" open><summary>{testResults[item.id]!.tools.length} tools discovered · {testResults[item.id]!.latencyMs} ms</summary>{testResults[item.id]!.tools.length ? testResults[item.id]!.tools.map(tool => <div key={tool.name}><strong>{tool.name}</strong><p>{tool.description || 'No description supplied.'}</p></div>) : <p>This server reports no tools.</p>}</details>}<footer><Button disabled={Boolean(testing)} busy={testing === item.id} onClick={() => { void test(item); }}>Test connection</Button><div><IconButton label={`Edit ${item.name}`} onClick={() => setEditing(item)}><Pencil size={16} /></IconButton><IconButton label={`Delete ${item.name}`} onClick={() => setDeleting(item)}><Trash2 size={16} /></IconButton></div></footer></article>)}</div> : <EmptyState icon={Cable} title="Connect your first tool server." action={<Button onClick={() => setEditing('new')}>Add MCP server</Button>}><p>Add a local command or a remote HTTP/SSE endpoint. Saved connections start disabled.</p></EmptyState>}
    {editing && <McpEditor item={editing === 'new' ? undefined : editing} onClose={() => setEditing(undefined)} onSaved={id => { servers.refresh(); setEditing(undefined); setTestResults(previous => { const copy = { ...previous }; if (id) delete copy[id]; return copy; }); notify('MCP server saved. Changes apply to new workspace runs.'); }} />}
    {deleting && <DeleteDialog title="Delete this MCP server?" onClose={() => setDeleting(undefined)} onDelete={async () => { await api(`/mcp/${segment(deleting.id)}`, { method: 'DELETE', body: JSON.stringify({ expectedVersion: deleting.version }) }); servers.refresh(); }}><p>Remove <strong>{deleting.name}</strong> and its saved credentials from this workspace. Existing runs keep their session connections until they finish.</p></DeleteDialog>}
  </div>;
}
function McpEditor({ item, onClose, onSaved }: { item?: McpServer; onClose: () => void; onSaved: (id?: string) => void }) {
  const { agents } = useWorkspace(); const [name, setName] = useState(item?.name || ''); const [transport, setTransport] = useState<McpInput['transport']>(item?.transport || 'http');
  const [command, setCommand] = useState(item?.command || ''); const [args, setArgs] = useState(item?.args?.join('\n') || ''); const [url, setUrl] = useState(item?.url || '');
  const [secrets, setSecrets] = useState(''); const [clear, setClear] = useState(false); const [enabled, setEnabled] = useState(item?.enabled || false); const [agentIds, setAgentIds] = useState(item?.agentIds || []);
  const [busy, setBusy] = useState(false); const [error, setError] = useState<string>();
  const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setError(undefined); try {
    let credentials: Record<string, string> | undefined; if (secrets.trim()) { const parsed: unknown = JSON.parse(secrets); if (!parsed || typeof parsed !== 'object' || Array.isArray(parsed) || Object.values(parsed).some(value => typeof value !== 'string')) throw new Error('Credentials must be a JSON object with string values.'); credentials = parsed as Record<string, string>; }
    const body = { name, transport, enabled, agentIds, clearCredentials: clear, ...(transport === 'stdio' ? { command, args: args ? args.split('\n') : [], ...(credentials ? { env: credentials } : {}) } : { url, ...(credentials ? { headers: credentials } : {}) }) };
    if (item) await api(`/mcp/${segment(item.id)}`, { method: 'PATCH', body: JSON.stringify({ ...body, expectedVersion: item.version }) }); else await post('/mcp', body); onSaved(item?.id);
  } catch (cause) { setError(cause instanceof SyntaxError ? 'Credentials must contain valid JSON.' : errorMessage(cause)); } finally { setBusy(false); } };
  return <Modal title={item ? 'Edit MCP server' : 'Add MCP server'} onClose={() => { if (!busy) onClose(); }} wide><form onSubmit={submit}><div className="modal-body control-form">{error && <ErrorNotice message={error} />}<div className="form-columns"><Field label="Server name"><input required maxLength={64} value={name} onChange={event => setName(event.target.value)} placeholder="my-tools" /></Field><Field label="Transport"><select value={transport} onChange={event => { setTransport(event.target.value as McpInput['transport']); setSecrets(''); }}><option value="http">Streamable HTTP</option><option value="sse">Server-sent events</option><option value="stdio">Local command (stdio)</option></select></Field></div>
    {transport === 'stdio' ? <><div className="control-note"><Server size={17} /><p>This command runs on the computer hosting the Super System API. In your local setup, that is your Mac.</p></div><Field label="Executable command" hint="Enter the executable path or command; put each argument below."><input required value={command} onChange={event => setCommand(event.target.value)} placeholder="npx" /></Field><Field label="Arguments" hint="One argument per line; no shell quoting needed."><textarea rows={3} value={args} onChange={event => setArgs(event.target.value)} placeholder={'-y\n@your/mcp-server'} /></Field></> : <Field label="Server URL" hint="Use headers for credentials. URLs cannot contain user information, query parameters, or fragments."><input type="url" required value={url} onChange={event => setUrl(event.target.value)} placeholder="https://tools.example.com/mcp" /></Field>}
    <Field label={transport === 'stdio' ? 'Environment variables (JSON)' : 'Headers (JSON)'} hint={item?.hasCredentials ? 'Credentials are saved. Leave this blank to preserve them; entering JSON replaces them.' : 'Optional. Stored only on the application server.'}><textarea className="code-editor" autoComplete="off" spellCheck={false} rows={3} value={secrets} onChange={event => setSecrets(event.target.value)} placeholder={transport === 'stdio' ? '{"API_KEY": "…"}' : '{"Authorization": "Bearer …"}'} /></Field>{item?.hasCredentials && <label className="check-row"><input type="checkbox" checked={clear} onChange={event => setClear(event.target.checked)} />Clear saved credentials</label>}<AgentAssignments agents={agents} value={agentIds} onChange={setAgentIds} /><label className="check-row"><input type="checkbox" checked={enabled} onChange={event => setEnabled(event.target.checked)} />Enable for assigned agents</label></div><div className="modal-footer"><Button type="button" disabled={busy} onClick={onClose}>Cancel</Button><Button type="submit" variant="primary" busy={busy}>Save server</Button></div></form></Modal>;
}
