import { useState, type FormEvent } from 'react';
import { ArrowRight, Bot, CircleDot, LayoutDashboard, Plus, Radio, Trash2 } from 'lucide-react';
import { isTerminal, taskStatuses, type OfficeSnapshot, type OfficeTask, type TaskInput } from '@super-system/core';
import { api, errorMessage, post, segment } from '../api';
import { useWorkspace } from '../context';
import { DeleteDialog, usePollingResource } from '../management-ui';
import { Badge, Button, EmptyState, ErrorNotice, Field, IconButton, Loading, Modal, PageHeader, relativeTime } from '../ui';
const labels = { backlog: 'Backlog', in_progress: 'In progress', blocked: 'Blocked', done: 'Done' };

export function Office() {
  const { preferences, setPreferences, setConversationId, navigate, inspectRun } = useWorkspace(); const office = usePollingResource<OfficeSnapshot>('/office', 10000);
  const [editing, setEditing] = useState<OfficeTask | 'new'>(); const [deleting, setDeleting] = useState<OfficeTask>(); const [agentFilter, setAgentFilter] = useState(''); const [error, setError] = useState<string>(); const [moving, setMoving] = useState<string>();
  const data = office.data; const tasks = (data?.tasks || []).filter(task => !agentFilter || task.agentId === agentFilter);
  const move = async (task: OfficeTask, status: OfficeTask['status']) => { setMoving(task.id); setError(undefined); try { const { title, description, agentId, priority } = task; await api(`/tasks/${segment(task.id)}`, { method: 'PATCH', body: JSON.stringify({ title, description, agentId, priority, status, expectedVersion: task.version }) }); office.refresh(); } catch (cause) { setError(errorMessage(cause)); } finally { setMoving(undefined); } };
  const openAgent = async (id: string) => { try { await setPreferences({ ...preferences, selectedAgentId: id }); setConversationId(undefined); navigate('chat'); } catch (cause) { setError(errorMessage(cause)); } };
  return <div className="page office-page"><PageHeader eyebrow="The office" title="A place for work to move." description="Your agents, a shared planning board, and the latest workspace activity." actions={<Button variant="primary" onClick={() => setEditing('new')}><Plus size={16} />New task</Button>} />
    {(error || office.error) && <ErrorNotice message={error || office.error!} retry={office.refresh} />}{!data ? <Loading /> : <><div className="office-toolbar"><div><span className="connection-dot online" />Refreshes every 10 seconds</div><Field label="Board agent"><select value={agentFilter} onChange={event => setAgentFilter(event.target.value)}><option value="">All agents</option>{data.agents.map(agent => <option key={agent.id} value={agent.id}>{agent.name} · {agent.id.slice(-8)}</option>)}</select></Field><Badge>{tasks.filter(task => task.status !== 'done').length} open tasks</Badge></div>
    <div className="office-layout"><section className="panel office-team"><div className="section-heading"><div><h2>At their desks</h2><p>Workspace activity</p></div><Bot size={19} /></div>{data.agents.length ? data.agents.map(agent => { const active = data.runs.find(run => run.agentId === agent.id && !isTerminal(run.status) && !run.releasedAt); return <button className={`office-desk ${active ? 'desk-active' : ''}`} key={agent.id} onClick={() => { void openAgent(agent.id); }}><span className="desk-illustration" aria-hidden="true"><span className="desk-monitor"><Bot size={21} /></span><span className="desk-surface" /><span className="desk-plant">✳</span></span><strong>{agent.name}</strong><small className="mono">{agent.id.slice(-8)}</small><Badge tone={active?.status === 'waiting_for_approval' || active?.status === 'interrupted' ? 'warn' : active ? 'good' : 'neutral'}>{active ? active.status.replaceAll('_', ' ') : 'No active workspace run'}</Badge><span className="desk-action">Open conversation <ArrowRight size={12} /></span></button>; }) : <EmptyState compact icon={Bot} title="No connected agents"><p>Your existing agents appear when the connection is available.</p></EmptyState>}</section>
    <section className="office-board" aria-label="Planning board">{taskStatuses.map(status => <section className={`board-lane lane-${status}`} key={status}><header><h2><CircleDot size={13} />{labels[status]}</h2><span>{tasks.filter(task => task.status === status).length}</span></header><div className="lane-cards">{tasks.filter(task => task.status === status).map(task => <article className="task-card" key={task.id}><div className="task-top"><span className={`priority-dot priority-${task.priority}`} /> <span>{task.priority} priority</span><IconButton label={`Delete task ${task.title}`} onClick={() => setDeleting(task)}><Trash2 size={13} /></IconButton></div><button className="task-title" onClick={() => setEditing(task)}>{task.title}</button>{task.description && <p>{task.description}</p>}<div className="task-assignee"><Bot size={13} /><span>{data.agents.find(agent => agent.id === task.agentId)?.name || (task.agentId ? 'Unavailable agent' : 'Unassigned')}</span></div><label className="task-status"><span className="sr-only">Status for {task.title}</span><select aria-label={`Status for ${task.title}`} value={task.status} disabled={Boolean(moving)} onChange={event => { void move(task, event.target.value as OfficeTask['status']); }}>{taskStatuses.map(value => <option value={value} key={value}>{labels[value]}</option>)}</select></label></article>)}{!tasks.some(task => task.status === status) && <div className="lane-empty">{status === 'backlog' ? <button onClick={() => setEditing('new')}><Plus size={15} />Add a task</button> : 'No tasks here'}</div>}</div></section>)}</section>
    <section className="panel office-feed"><div className="section-heading"><div><h2>Live feed</h2><p>Recent workspace events</p></div><Radio size={18} /></div><div className="office-events">{data.activity.filter(item => !agentFilter || item.agentId === agentFilter).slice(0, 30).map(item => { const run = data.runs.find(run => run.id === item.runId); return <button key={item.id} className="office-event" disabled={!run} onClick={() => run && inspectRun(run)}><span className={`event-dot event-${item.status || item.type}`} /><span><strong>{item.title}</strong>{item.description && <p>{item.description}</p>}<time title={item.createdAt}>{relativeTime(item.createdAt)}</time></span></button>; })}{!data.activity.length && <p className="panel-padding muted">Your workspace activity will appear here.</p>}</div></section></div>
    <div className="control-note"><LayoutDashboard size={17} /><p>This board organizes plans. Moving a task does not start or stop an agent. Open an agent’s conversation to give it work; run approvals and recovery remain in the conversation.</p></div></>}
    {editing && <TaskEditor item={editing === 'new' ? undefined : editing} agents={data?.agents || []} onClose={() => setEditing(undefined)} onSaved={() => { setEditing(undefined); office.refresh(); }} />}
    {deleting && <DeleteDialog title="Delete this planning task?" onClose={() => setDeleting(undefined)} onDelete={async () => { await api(`/tasks/${segment(deleting.id)}`, { method: 'DELETE', body: JSON.stringify({ expectedVersion: deleting.version }) }); office.refresh(); }}><p>Delete <strong>{deleting.title}</strong> from the board. Agent runs and conversations are unaffected.</p></DeleteDialog>}
  </div>;
}
function TaskEditor({ item, agents, onClose, onSaved }: { item?: OfficeTask; agents: OfficeSnapshot['agents']; onClose: () => void; onSaved: () => void }) {
  const [draft, setDraft] = useState<TaskInput>(item || { title: '', description: '', status: 'backlog', priority: 'normal' }); const [busy, setBusy] = useState(false); const [error, setError] = useState<string>();
  const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setError(undefined); try { const { title, description, agentId, status, priority } = draft; const body = { title, description, agentId, status, priority }; if (item) await api(`/tasks/${segment(item.id)}`, { method: 'PATCH', body: JSON.stringify({ ...body, expectedVersion: item.version }) }); else await post('/tasks', body); onSaved(); } catch (cause) { setError(errorMessage(cause)); } finally { setBusy(false); } };
  return <Modal title={item ? 'Edit task' : 'New task'} onClose={() => { if (!busy) onClose(); }}><form onSubmit={submit}><div className="modal-body control-form">{error && <ErrorNotice message={error} />}<Field label="Task title"><input required maxLength={200} value={draft.title} onChange={event => setDraft({ ...draft, title: event.target.value })} /></Field><Field label="Task description"><textarea rows={5} maxLength={10000} value={draft.description} onChange={event => setDraft({ ...draft, description: event.target.value })} /></Field><Field label="Assigned agent"><select value={draft.agentId || ''} onChange={event => setDraft({ ...draft, agentId: event.target.value || undefined })}><option value="">Unassigned</option>{agents.map(agent => <option key={agent.id} value={agent.id}>{agent.name} · {agent.id.slice(-8)}</option>)}</select></Field><div className="form-columns"><Field label="Task status"><select value={draft.status} onChange={event => setDraft({ ...draft, status: event.target.value as TaskInput['status'] })}>{taskStatuses.map(status => <option key={status} value={status}>{labels[status]}</option>)}</select></Field><Field label="Priority"><select value={draft.priority} onChange={event => setDraft({ ...draft, priority: event.target.value as TaskInput['priority'] })}><option value="low">Low</option><option value="normal">Normal</option><option value="high">High</option></select></Field></div></div><div className="modal-footer"><Button type="button" disabled={busy} onClick={onClose}>Cancel</Button><Button type="submit" busy={busy} variant="primary">Save task</Button></div></form></Modal>;
}
