import { useState, type FormEvent } from 'react';
import { BookOpen, FileUp, Pencil, Plus, Trash2 } from 'lucide-react';
import type { SkillInput, WorkspaceSkill } from '@super-system/core';
import { api, errorMessage, post, segment } from '../api';
import { useWorkspace } from '../context';
import { useResource } from '../hooks';
import { AgentAssignments, DeleteDialog } from '../management-ui';
import { Badge, Button, EmptyState, ErrorNotice, Field, IconButton, Loading, Markdown, Modal, PageHeader, SearchField } from '../ui';

export function Skills() {
  const { agents, notify } = useWorkspace(); const skills = useResource<WorkspaceSkill[]>('/skills');
  const [search, setSearch] = useState(''); const [editing, setEditing] = useState<WorkspaceSkill | 'new'>(); const [viewing, setViewing] = useState<WorkspaceSkill>(); const [deleting, setDeleting] = useState<WorkspaceSkill>();
  const items = (skills.data || []).filter(item => `${item.name} ${item.description}`.toLowerCase().includes(search.toLowerCase()));
  return <div className="page control-page"><PageHeader eyebrow="Your agent’s playbook" title="Skills that travel with you." description="Reusable instructions for the way you like work to be done." actions={<Button variant="primary" onClick={() => setEditing('new')}><Plus size={16} />New skill</Button>} />
    <div className="control-toolbar"><SearchField value={search} onChange={setSearch} placeholder="Find a skill…" /><Badge>{skills.data?.length || 0} skills</Badge></div>
    <div className="control-note"><BookOpen size={17} /><p>Enabled skills are included in new messages sent here to their assigned agents. This library stores workspace instructions; it does not list skills installed on your VPS.</p></div>
    {skills.error && <ErrorNotice message={skills.error} retry={skills.refresh} />}{skills.loading && !skills.data ? <Loading /> : items.length ? <div className="control-card-grid">{items.map(item => <article className="panel control-card" key={item.id}><div className="control-card-top"><span className="control-symbol"><BookOpen size={21} /></span><Badge tone={item.enabled && item.agentIds.length ? 'good' : 'neutral'}>{item.enabled ? item.agentIds.length ? 'Enabled' : 'Unassigned' : 'Disabled'}</Badge></div><h2><button className="heading-button" onClick={() => setViewing(item)}>{item.name}</button></h2><p>{item.description || 'Open this skill to read its instructions.'}</p><div className="assignment-tags">{item.agentIds.map(id => <span key={id}>{agents.find(agent => agent.id === id)?.name || id.slice(-8)}</span>)}</div><footer><Button variant="ghost" onClick={() => setViewing(item)}>Read skill</Button><div><IconButton label={`Edit ${item.name}`} onClick={() => setEditing(item)}><Pencil size={16} /></IconButton><IconButton label={`Delete ${item.name}`} onClick={() => setDeleting(item)}><Trash2 size={16} /></IconButton></div></footer></article>)}</div> : <EmptyState icon={BookOpen} title={search ? 'No matching skills' : 'Give good instructions a home.'} action={!search && <Button onClick={() => setEditing('new')}>Create your first skill</Button>}><p>{search ? 'Try a different name or description.' : 'Save a research method, writing style, or review checklist and assign it to an agent.'}</p></EmptyState>}
    {editing && <SkillEditor item={editing === 'new' ? undefined : editing} onClose={() => setEditing(undefined)} onSaved={() => { skills.refresh(); setEditing(undefined); notify('Skill saved. It applies to new workspace runs.'); }} />}
    {viewing && <Modal title={viewing.name} onClose={() => setViewing(undefined)} wide><div className="modal-body skill-preview"><Markdown>{viewing.content}</Markdown></div><div className="modal-footer"><Button onClick={() => { setEditing(viewing); setViewing(undefined); }}>Edit skill</Button></div></Modal>}
    {deleting && <DeleteDialog title="Delete this skill?" onClose={() => setDeleting(undefined)} onDelete={async () => { await api(`/skills/${segment(deleting.id)}`, { method: 'DELETE', body: JSON.stringify({ expectedVersion: deleting.version }) }); skills.refresh(); }}><p>Remove <strong>{deleting.name}</strong> from the workspace library. Existing conversations keep their history.</p></DeleteDialog>}
  </div>;
}
function SkillEditor({ item, onClose, onSaved }: { item?: WorkspaceSkill; onClose: () => void; onSaved: () => void }) {
  const { agents } = useWorkspace(); const [draft, setDraft] = useState<SkillInput>(item || { name: '', description: '', content: '', agentIds: [], enabled: false });
  const [busy, setBusy] = useState(false); const [error, setError] = useState<string>();
  const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setError(undefined); try { const body = { name: draft.name, description: draft.description, content: draft.content, agentIds: draft.agentIds, enabled: draft.enabled }; if (item) await api(`/skills/${segment(item.id)}`, { method: 'PATCH', body: JSON.stringify({ ...body, expectedVersion: item.version }) }); else await post('/skills', body); onSaved(); } catch (cause) { setError(errorMessage(cause)); } finally { setBusy(false); } };
  return <Modal title={item ? 'Edit skill' : 'New skill'} onClose={() => { if (!busy) onClose(); }} wide><form onSubmit={submit}><div className="modal-body control-form">{error && <ErrorNotice message={error} />}<div className="form-columns"><Field label="Skill name"><input required maxLength={100} value={draft.name} onChange={event => setDraft({ ...draft, name: event.target.value })} /></Field><Field label="Short description"><input maxLength={500} value={draft.description} onChange={event => setDraft({ ...draft, description: event.target.value })} /></Field></div><label className="file-import"><FileUp size={16} />Import a Markdown file<input type="file" accept=".md,.txt,text/markdown,text/plain" onChange={async event => { const file = event.target.files?.[0]; if (!file) return; if (file.size > 200000) { setError('Choose a text file smaller than 200 KB.'); return; } try { const content = await file.text(); if (content.length > 50000) { setError('Keep skill instructions under 50,000 characters.'); return; } setDraft(previous => ({ ...previous, content, name: previous.name || file.name.replace(/\.md$/i, '') })); } catch { setError('This file could not be read.'); } }} /></label><Field label="Instructions" hint="Markdown is supported. Review imported instructions before enabling them."><textarea required className="code-editor" rows={12} maxLength={50000} value={draft.content} onChange={event => setDraft({ ...draft, content: event.target.value })} /></Field><AgentAssignments agents={agents} value={draft.agentIds} onChange={agentIds => setDraft({ ...draft, agentIds })} /><label className="check-row"><input type="checkbox" checked={draft.enabled} onChange={event => setDraft({ ...draft, enabled: event.target.checked })} />Enable for assigned agents</label></div><div className="modal-footer"><Button disabled={busy} type="button" onClick={onClose}>Cancel</Button><Button variant="primary" type="submit" busy={busy}>Save skill</Button></div></form></Modal>;
}
