import { useState } from 'react';
import { Check, ChevronRight, CircleHelp, Globe2, Laptop, Link2, Monitor, Moon, RefreshCw, Server, ShieldCheck, Sun } from 'lucide-react';
import { capabilityKeys, type Machine, type SystemInfo } from '@super-system/core';
import { useWorkspace } from '../context';
import { useResource } from '../hooks';
import { errorMessage } from '../api';
import { Badge, Button, CapabilityNotice, CopyButton, dateTime, EmptyState, ErrorNotice, Field, Loading, PageHeader } from '../ui';

const capabilityNames: Record<string, string> = { chat: 'Agent chat', conversations: 'Conversations', cancel: 'Cancel a run', approvals: 'Tool approvals', memoryRead: 'Read memory', memoryWrite: 'Edit memory', files: 'Attached files', routinesRead: 'View routines', routinesWrite: 'Manage routines', routineRun: 'Run on demand', routinePause: 'Pause routines', machines: 'Machine status', agentConfigRead: 'Read agent configuration', agentConfigWrite: 'Edit agent configuration', gateway: 'Runtime diagnostics', mcp: 'Session MCP tools' };
export function System() {
  const { connection, agent, preferences, setPreferences, refreshConnection, notify } = useWorkspace();
  const system = useResource<SystemInfo>('/system');
  const machines = useResource<Machine[]>(connection.capabilities.machines.state === 'supported' ? '/machines' : null);
  const [checking, setChecking] = useState(false);
  const [timezone, setTimezone] = useState(preferences.timezone);
  const [saving, setSaving] = useState(false);
  const check = async () => { setChecking(true); try { await refreshConnection(); system.refresh(); machines.refresh(); } catch (error) { notify(errorMessage(error), 'bad'); } finally { setChecking(false); } };
  const saveTimezone = async () => {
    try { new Intl.DateTimeFormat(undefined, { timeZone: timezone }); } catch { notify('Enter an IANA timezone, such as Europe/Vienna.', 'bad'); return; }
    setSaving(true); try { await setPreferences({ ...preferences, timezone }); notify('Timezone saved.'); } catch (error) { notify(errorMessage(error), 'bad'); } finally { setSaving(false); }
  };
  return <div className="page system-page"><PageHeader eyebrow="Workspace settings" title="A healthy connection." description="Your server, preferences, and the details behind your workspace." actions={<Button busy={checking} onClick={check}><RefreshCw size={15} /> Check connection</Button>} />
    <section className="panel connection-panel"><div className="section-heading"><div className="heading-with-icon"><div className="section-icon"><Server size={20} /></div><div><h2>Letta connection</h2><p>Your existing agent runs here.</p></div></div><Badge tone={connection.status === 'connected' ? 'good' : connection.status === 'error' ? 'bad' : 'neutral'}>{connection.status === 'connected' ? 'Connected' : connection.status === 'error' ? 'Connection failed' : 'Not connected'}</Badge></div>
      {connection.configured ? <><dl className="detail-grid"><div><dt>Server</dt><dd className="mono wrap-anywhere">{connection.baseUrl || connection.label}</dd></div><div><dt>Integration</dt><dd>{connection.mode === 'legacy' ? 'Letta REST API' : 'Letta App Server'}</dd></div><div><dt>Runtime version</dt><dd>{connection.version || 'Not reported by server'}</dd></div><div><dt>Response time</dt><dd>{connection.latencyMs !== undefined ? `${connection.latencyMs} ms` : 'Not available'}</dd></div><div><dt>Last checked</dt><dd>{dateTime(connection.checkedAt, preferences.timezone)}</dd></div><div><dt>Agent</dt><dd className="mono wrap-anywhere">{agent?.id || connection.agentId || 'Choose an available agent in the sidebar'}</dd></div></dl>{connection.error && <ErrorNotice message={connection.error} retry={check} />}</> : <div className="connection-setup"><div><h3>Connect your Hetzner server</h3><p>Set the connection in the application server’s <code>.env</code> file, then restart it. Your credentials stay on the server.</p><ol><li>Choose <strong>legacy</strong> for the REST API or <strong>app-server</strong> for Letta App Server.</li><li>Enter your service URL and the existing agent ID.</li><li>Add the matching API key or server token, then check the connection.</li></ol></div><div className="config-example"><div><span>.env</span><CopyButton label="Copy example" text={'LETTA_MODE=legacy\nLETTA_BASE_URL=https://your-letta-server\nLETTA_AGENT_ID=your-existing-agent-id\nLETTA_API_KEY=your-api-key'} /></div><pre>{'LETTA_MODE=legacy\nLETTA_BASE_URL=https://your-letta-server\nLETTA_AGENT_ID=your-existing-agent-id\nLETTA_API_KEY=your-api-key'}</pre><p>App Server connections use <code>LETTA_SERVER_TOKEN</code>.</p></div></div>}
      <div className="panel-footnote"><ShieldCheck size={15} />Provider credentials are never exposed to this interface.</div>
    </section>
    <div className="system-columns"><section className="panel"><div className="section-heading"><div><h2>Make it yours</h2><p>A quieter workspace, your way.</p></div></div><div className="preferences-body"><span className="field-label">Appearance</span><div className="theme-choices">{([{ value: 'light', icon: Sun, label: 'Light' }, { value: 'dark', icon: Moon, label: 'Dark' }, { value: 'system', icon: Monitor, label: 'System' }] as const).map(({ value, icon: Icon, label }) => <button key={value} className={`theme-choice ${preferences.theme === value ? 'selected' : ''}`} aria-pressed={preferences.theme === value} onClick={() => { void setPreferences({ ...preferences, theme: value }).catch(error => notify(errorMessage(error), 'bad')); }}><div className={`theme-preview preview-${value}`}><span /><span /><span /></div><span><Icon size={14} />{label}{preferences.theme === value && <Check size={13} />}</span></button>)}</div><Field label="Display timezone" hint="Dates in your workspace use this timezone. Routine execution uses each schedule’s own timezone."><input value={timezone} onChange={event => setTimezone(event.target.value)} placeholder="Europe/Vienna" /></Field><Button busy={saving} disabled={timezone === preferences.timezone} onClick={saveTimezone}>Save preference <ChevronRight size={14} /></Button></div></section>
    <section className="panel"><div className="section-heading"><div><h2>About this workspace</h2><p>The application behind the interface.</p></div></div>{system.error ? <ErrorNotice message={system.error} retry={system.refresh} /> : system.data ? <dl className="settings-list"><div><dt>Application</dt><dd>Super System <span className="mono">v{system.data.version}</span></dd></div><div><dt>Environment</dt><dd>{system.data.environment}</dd></div><div><dt>Storage</dt><dd>{system.data.persistence === 'postgres' ? 'PostgreSQL' : 'Local persistent file'}</dd></div><div><dt>Access</dt><dd>{system.data.authRequired ? 'Password protected' : 'Local access only'}</dd></div><div><dt>Server uptime</dt><dd>{Math.floor(system.data.uptime / 3600)}h {Math.floor(system.data.uptime % 3600 / 60)}m</dd></div><div className="settings-text"><dt>History coverage</dt><dd>{system.data.historyCoverage}</dd></div></dl> : <Loading />}</section></div>
    <section className="panel"><div className="section-heading"><div><h2>Connection capabilities</h2><p>Available features depend on the version and configuration of your server.</p></div><CircleHelp size={18} className="muted" /></div><div className="capability-grid">{capabilityKeys.map(key => <div key={key} className="capability-row"><div><span>{capabilityNames[key]}</span>{connection.capabilities[key].reason && <small>{connection.capabilities[key].reason}</small>}</div><Badge tone={connection.capabilities[key].state === 'supported' ? 'good' : 'neutral'}>{connection.capabilities[key].state === 'supported' ? 'Available' : connection.capabilities[key].state === 'unsupported' ? 'Unsupported' : 'Unavailable'}</Badge></div>)}</div></section>
    <section className="panel"><div className="section-heading"><div className="heading-with-icon"><Laptop size={19} /><div><h2>Connected machines</h2><p>Execution targets reported by Letta.</p></div></div></div>{connection.capabilities.machines.state !== 'supported' ? <CapabilityNotice capability={connection.capabilities.machines} icon={Laptop} title="Machine status is unavailable" /> : machines.error ? <ErrorNotice message={machines.error} retry={machines.refresh} /> : machines.loading && !machines.data ? <Loading /> : machines.data?.length ? <div className="machine-list">{machines.data.map(machine => <div key={machine.id}><div className="section-icon"><Laptop size={20} /></div><div><h3>{machine.name}</h3><p>{[machine.platform, machine.kind, machine.version].filter(Boolean).join(' · ') || machine.id}</p><small>Last seen: {dateTime(machine.lastSeenAt, preferences.timezone)}</small></div><Badge tone={machine.status === 'online' ? 'good' : 'neutral'}>{machine.status}</Badge></div>)}</div> : <EmptyState compact icon={Laptop} title="No machines reported"><p>Registered execution targets will appear here.</p></EmptyState>}</section>
    <div className="home-footnote"><Globe2 size={14} /><span>One workspace in your browser and desktop. Closing either leaves server-owned work running.</span><Link2 size={14} /></div>
  </div>;
}
