import { useState } from 'react';
import { BarChart3, Download } from 'lucide-react';
import type { UsageReport } from '@super-system/core';
import { query } from '../api';
import { useWorkspace } from '../context';
import { useResource } from '../hooks';
import { formatCount, Metrics } from '../management-ui';
import { Button, ErrorNotice, Field, Loading, PageHeader } from '../ui';

export function Usage() {
  const { agents } = useWorkspace(); const [days, setDays] = useState(30); const [agentId, setAgentId] = useState(''); const usage = useResource<UsageReport>(`/usage${query({ days, agentId: agentId || undefined })}`); const data = usage.data;
  const exportCsv = () => { if (!data) return; const rows = [['date_utc', 'runs', 'completed', 'failed', 'input_tokens', 'output_tokens', 'total_tokens', 'reported_cost_usd', 'duration_ms', 'token_measured_runs', 'cost_measured_runs'], ...data.daily.map(day => [day.date, day.runs, day.completed, day.failed, day.inputTokens, day.outputTokens, day.totalTokens, day.costUsd, day.durationMs, day.tokenMeasuredRuns, day.costMeasuredRuns])]; const csv = rows.map(row => row.map(value => value == null ? '' : String(value)).join(',')).join('\r\n'); const url = URL.createObjectURL(new Blob([csv], { type: 'text/csv;charset=utf-8;' })); const a = document.createElement('a'); a.href = url; a.download = `super-system-usage-${data.to.slice(0, 10)}.csv`; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); };
  const maximum = Math.max(1, ...data?.daily.map(day => day.totalTokens || 0) || []);
  return <div className="page control-page"><PageHeader eyebrow="Workspace analytics" title="Understand your usage." description="A measured view of your agents’ work, with clear limits on what is known." actions={<Button disabled={!data} onClick={exportCsv}><Download size={15} />Export CSV</Button>} /><div className="control-toolbar usage-filters"><Field label="Period"><select value={days} onChange={event => setDays(Number(event.target.value))}><option value={7}>Last 7 days</option><option value={30}>Last 30 days</option><option value={90}>Last 90 days</option></select></Field><Field label="Agent filter"><select value={agentId} onChange={event => setAgentId(event.target.value)}><option value="">All agents</option>{agents.map(agent => <option key={agent.id} value={agent.id}>{agent.name} · {agent.id.slice(-8)}</option>)}</select></Field><span className="quiet-label">Daily boundaries: UTC</span></div>
    {usage.error && <ErrorNotice message={usage.error} retry={usage.refresh} />}{!data ? <Loading /> : <><Metrics values={[{ label: 'Workspace runs', value: formatCount(data.totals.runs), detail: `${data.totals.completed} completed · ${data.totals.failed} failed` }, { label: 'Reported tokens', value: formatCount(data.totals.totalTokens), detail: `${data.totals.tokenMeasuredRuns} of ${data.totals.runs} runs measured` }, { label: 'Reported cost', value: data.totals.costUsd == null ? '—' : new Intl.NumberFormat(undefined, { style: 'currency', currency: 'USD', maximumFractionDigits: 4 }).format(data.totals.costUsd), detail: `${data.totals.costMeasuredRuns} of ${data.totals.runs} runs measured` }, { label: 'Measured run time', value: data.totals.durationMs == null ? '—' : `${(data.totals.durationMs / 1000).toFixed(1)}s`, detail: `${data.totals.durationMeasuredRuns} runs measured` }]} />
    <section className="panel usage-chart-panel"><div className="section-heading"><div><h2>Tokens over time</h2><p>Reported token counts per day. Unmeasured days remain empty.</p></div><BarChart3 size={19} /></div><div className="usage-chart" role="img" aria-label={`Daily reported token usage for the last ${days} days. Exact values are available in the daily table below.`}>{data.daily.map(day => <div className="usage-bar-column" key={day.date} title={`${day.date}: ${day.totalTokens == null ? 'No measurement' : day.totalTokens + ' tokens'}`}><div className={`usage-bar ${day.totalTokens == null ? 'unmeasured' : ''}`} style={{ height: `${day.totalTokens == null ? 2 : Math.max(2, day.totalTokens / maximum * 100)}%` }} /></div>)}</div><div className="chart-axis"><span>{data.from.slice(0, 10)}</span><span>{data.to.slice(0, 10)}</span></div></section>
    <div className="control-note"><BarChart3 size={17} /><p>{data.coverage}</p></div><section className="panel"><div className="section-heading"><div><h2>By agent</h2><p>Reported measurements within the selected period.</p></div></div><div className="control-table-wrap"><table className="control-table"><thead><tr><th>Agent</th><th>Runs</th><th>Input tokens</th><th>Output tokens</th><th>Total tokens</th></tr></thead><tbody>{data.agents.length ? data.agents.map(agent => <tr key={agent.agentId}><td><strong>{agent.name}</strong><small className="mono">{agent.agentId.slice(-8)}</small></td><td>{agent.runs}</td><td>{formatCount(agent.inputTokens)}</td><td>{formatCount(agent.outputTokens)}</td><td>{formatCount(agent.totalTokens)}</td></tr>) : <tr><td colSpan={5}>No workspace runs in this period.</td></tr>}</tbody></table></div></section><details className="panel daily-details"><summary>Daily measurements</summary><div className="control-table-wrap"><table className="control-table"><thead><tr><th>Date (UTC)</th><th>Runs</th><th>Tokens</th><th>Reported cost (USD)</th></tr></thead><tbody>{[...data.daily].reverse().map(day => <tr key={day.date}><td>{day.date}</td><td>{day.runs}</td><td>{formatCount(day.totalTokens)}</td><td>{day.costUsd == null ? '—' : day.costUsd.toFixed(4)}</td></tr>)}</tbody></table></div></details></>}
  </div>;
}
